/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedShortlistEvaluatorRouteImport } from './routes/_authenticated/shortlist-evaluator'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedGuesstimatesRouteImport } from './routes/_authenticated/guesstimates'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedScorecardIdRouteImport } from './routes/_authenticated/scorecard.$id'
import { Route as AuthenticatedInterviewIdRouteImport } from './routes/_authenticated/interview.$id'
import { Route as AuthenticatedGuesstimateIdRouteImport } from './routes/_authenticated/guesstimate.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShortlistEvaluatorRoute =
  AuthenticatedShortlistEvaluatorRouteImport.update({
    id: '/shortlist-evaluator',
    path: '/shortlist-evaluator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuesstimatesRoute =
  AuthenticatedGuesstimatesRouteImport.update({
    id: '/guesstimates',
    path: '/guesstimates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScorecardIdRoute =
  AuthenticatedScorecardIdRouteImport.update({
    id: '/scorecard/$id',
    path: '/scorecard/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewIdRoute =
  AuthenticatedInterviewIdRouteImport.update({
    id: '/interview/$id',
    path: '/interview/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuesstimateIdRoute =
  AuthenticatedGuesstimateIdRouteImport.update({
    id: '/guesstimate/$id',
    path: '/guesstimate/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guesstimates': typeof AuthenticatedGuesstimatesRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/new': typeof AuthenticatedNewRoute
  '/shortlist-evaluator': typeof AuthenticatedShortlistEvaluatorRoute
  '/guesstimate/$id': typeof AuthenticatedGuesstimateIdRoute
  '/interview/$id': typeof AuthenticatedInterviewIdRoute
  '/scorecard/$id': typeof AuthenticatedScorecardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guesstimates': typeof AuthenticatedGuesstimatesRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/new': typeof AuthenticatedNewRoute
  '/shortlist-evaluator': typeof AuthenticatedShortlistEvaluatorRoute
  '/guesstimate/$id': typeof AuthenticatedGuesstimateIdRoute
  '/interview/$id': typeof AuthenticatedInterviewIdRoute
  '/scorecard/$id': typeof AuthenticatedScorecardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/guesstimates': typeof AuthenticatedGuesstimatesRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/shortlist-evaluator': typeof AuthenticatedShortlistEvaluatorRoute
  '/_authenticated/guesstimate/$id': typeof AuthenticatedGuesstimateIdRoute
  '/_authenticated/interview/$id': typeof AuthenticatedInterviewIdRoute
  '/_authenticated/scorecard/$id': typeof AuthenticatedScorecardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/guesstimates'
    | '/history'
    | '/new'
    | '/shortlist-evaluator'
    | '/guesstimate/$id'
    | '/interview/$id'
    | '/scorecard/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/guesstimates'
    | '/history'
    | '/new'
    | '/shortlist-evaluator'
    | '/guesstimate/$id'
    | '/interview/$id'
    | '/scorecard/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/guesstimates'
    | '/_authenticated/history'
    | '/_authenticated/new'
    | '/_authenticated/shortlist-evaluator'
    | '/_authenticated/guesstimate/$id'
    | '/_authenticated/interview/$id'
    | '/_authenticated/scorecard/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shortlist-evaluator': {
      id: '/_authenticated/shortlist-evaluator'
      path: '/shortlist-evaluator'
      fullPath: '/shortlist-evaluator'
      preLoaderRoute: typeof AuthenticatedShortlistEvaluatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guesstimates': {
      id: '/_authenticated/guesstimates'
      path: '/guesstimates'
      fullPath: '/guesstimates'
      preLoaderRoute: typeof AuthenticatedGuesstimatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scorecard/$id': {
      id: '/_authenticated/scorecard/$id'
      path: '/scorecard/$id'
      fullPath: '/scorecard/$id'
      preLoaderRoute: typeof AuthenticatedScorecardIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/$id': {
      id: '/_authenticated/interview/$id'
      path: '/interview/$id'
      fullPath: '/interview/$id'
      preLoaderRoute: typeof AuthenticatedInterviewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guesstimate/$id': {
      id: '/_authenticated/guesstimate/$id'
      path: '/guesstimate/$id'
      fullPath: '/guesstimate/$id'
      preLoaderRoute: typeof AuthenticatedGuesstimateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGuesstimatesRoute: typeof AuthenticatedGuesstimatesRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedShortlistEvaluatorRoute: typeof AuthenticatedShortlistEvaluatorRoute
  AuthenticatedGuesstimateIdRoute: typeof AuthenticatedGuesstimateIdRoute
  AuthenticatedInterviewIdRoute: typeof AuthenticatedInterviewIdRoute
  AuthenticatedScorecardIdRoute: typeof AuthenticatedScorecardIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGuesstimatesRoute: AuthenticatedGuesstimatesRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedShortlistEvaluatorRoute: AuthenticatedShortlistEvaluatorRoute,
  AuthenticatedGuesstimateIdRoute: AuthenticatedGuesstimateIdRoute,
  AuthenticatedInterviewIdRoute: AuthenticatedInterviewIdRoute,
  AuthenticatedScorecardIdRoute: AuthenticatedScorecardIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
